replicaCount: 1

image:
  repository: gcr.io/aremko-e51ae/remity-frontend
  pullPolicy: Always
  tag: "v3"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: remity.io
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: remity-io-tls
      hosts:
        - remity.io

resources: {}
