apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remity-backend.fullname" . }}
  labels:
    {{- include "remity-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "remity-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "remity-backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: POSTGRES_SERVER
              value: {{ .Values.database.host }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.secretName }}
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.database.name }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
