services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Specify the Dockerfile
    container_name: remity_backend_dev
    # Embed entrypoint logic directly here, bypassing the script file
    command: >
      bash -c "
        echo 'Backend container started...';
        echo 'Waiting for database server at ${POSTGRES_HOST}:${POSTGRES_PORT}...';
        while ! pg_isready -h \"${POSTGRES_HOST}\" -p \"${POSTGRES_PORT}\" -U \"${POSTGRES_USER}\" -q; do
          echo 'PostgreSQL server is unavailable - sleeping';
          sleep 1;
        done;
        echo 'PostgreSQL server is up.';

        check_db() {
            pg_isready -h \"${POSTGRES_HOST}\" -p \"${POSTGRES_PORT}\" -U \"${POSTGRES_USER}\" -d \"${POSTGRES_DB}\" -q;
        };

        if ! check_db; then
            echo 'Database ${POSTGRES_DB} not found or not ready. Attempting to create...';
            export PGPASSWORD=\"${POSTGRES_PASSWORD}\";
            createdb -h \"${POSTGRES_HOST}\" -p \"${POSTGRES_PORT}\" -U \"${POSTGRES_USER}\" \"${POSTGRES_DB}\" || echo 'Database creation failed or DB already exists.';
            unset PGPASSWORD;
            sleep 2;
            echo 'Waiting for database ${POSTGRES_DB} to become ready after creation attempt...';
            while ! check_db; do
              echo 'Database ${POSTGRES_DB} is still unavailable - sleeping';
              sleep 1;
            done;
        fi;
        echo 'Database ${POSTGRES_DB} is ready.';

        echo 'Applying database migrations...';
        alembic -c /app/alembic.ini upgrade head;
        echo 'Migrations applied.';

        echo 'Running initial data script...';
        python -m app.initial_data --email admin@remity.io --password simon144610;
        echo 'Initial data script completed.';

        echo 'Starting application: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload';
        exec uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload;
      "
    volumes:
      - ./backend:/app
    ports:
      # Map host port 8001 to container port 8000 to avoid conflicts
      - "8001:8000"
    env_file:
      # Load environment variables from the .env file in the backend directory
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - remity_network
    # Add healthcheck for backend if needed later

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Specify the Dockerfile
    container_name: remity_frontend_dev
    volumes:
      # Mount frontend code for development changes
      - ./frontend:/app
      # Persist node_modules separately to avoid overwriting by host mount
      - /app/node_modules
    ports:
      # Map host port 3000 to container port 3000
      - "3000:3000"
    environment:
      # Ensure hot-reloading works well in Docker
      - WATCHPACK_POLLING=true
      # Pass API URL to React app (pointing to the HOST port mapped from backend)
      - REACT_APP_API_BASE_URL=http://localhost:8001/api/v1
    depends_on:
      - backend # Frontend depends on backend being available (though requests might fail initially)
    networks:
      - remity_network
    # Command to start the React development server
    command: npm start

  db:
    image: postgres:15-alpine # Use a specific, stable version
    container_name: remity_db_dev
    volumes:
      # Use a named volume for persistent data storage
      - postgres_data:/var/lib/postgresql/data/
    # Load environment variables directly from the file for the container
    env_file:
      - ./backend/.env
    ports:
      # Expose PostgreSQL port to the host (optional, for direct access)
      - "5432:5432"
    networks:
      - remity_network
    healthcheck:
      # Check if PostgreSQL is ready to accept connections
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s # Check every 10 seconds
      timeout: 5s   # Wait up to 5 seconds for the check
      retries: 5    # Retry 5 times before marking as unhealthy

  redis:
    image: redis:7-alpine # Use a specific, stable version
    container_name: remity_redis_dev
    ports:
      # Expose Redis port to the host (optional, for direct access)
      # Map host port 6380 to container port 6379 to avoid conflicts
      - "6380:6379"
    networks:
      - remity_network
    healthcheck:
      # Check if Redis server is responding to ping
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # Define the named volume for PostgreSQL data
  postgres_data:
    driver: local

networks:
  # Define the network for services to communicate
  remity_network:
    driver: bridge
