apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "remity-frontend.fullname" . }}
  labels:
    {{- include "remity-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "remity-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "remity-frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
